---
version: '3.3'
services:
  crawler:
    image: wildermesser/crawler:latest
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    command: sh -c './wait-for rabbitmq:5672 -t 120 -- python crawler.py https://vitkhab.github.io/search_engine_test_site/'
    environment:
      RMQ_PASSWORD: crawler
    networks:
      - crawler_net
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/sb
    networks:
      - crawler_net
  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: crawler
      RABBITMQ_DEFAULT_PASS: crawler
    networks:
      - crawler_net
  ui:
    image: wildermesser/ui:latest
    restart: always
    depends_on:
      - crawler
    networks: 
      - crawler_net
    ports:
      - 8000:8000
  telegraf:
    image: telegraf:1.7-alpine
    command: -config /etc/telegraf/telegraf.conf 
    restart: always
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - crawler_net
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.3.2
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro  
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - crawler_net    
networks:
  crawler_net:

volumes:
  mongo_data:




  