filebeat.inputs:
- type: docker
  containers.ids: '*'
  json.ignore_decoding_error: true

output.elasticsearch:
  hosts: ["logging.ocrawler.tk:9200"]

setup.kibana:
  host: "http://logging.ocrawler.tk:80".

logging.to_files: true
logging.to_syslog: false
