version: '3.3'
services:
  jenkins:
    image: jenkinsci/blueocean
    privileged: true
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  jenkins-data:
